export const COMMAND_IDS = [
  'file.new',
  'file.open',
  'file.save',
  'file.saveAs',
  'format.bold',
  'format.italic',
  'format.strike',
  'format.code',
  'format.clearFormat',
  'format.heading1',
  'format.heading2',
  'format.heading3',
  'format.heading4',
  'format.heading5',
  'format.heading6',
  'format.paragraph',
  'format.blockquote',
  'format.orderedList',
  'format.unorderedList',
  'format.codeFences',
  'format.table',
  'format.hyperlink',
  'format.image',
  'view.toggleSidebar',
  'view.outline',
  'view.sourceMode',
  'view.focusMode',
  'view.typewriterMode',
] as const;

export type CommandId = (typeof COMMAND_IDS)[number];
